### ISSUE TITLE
スマホだと重すぎて見えないので調整する

### ISSUE THREAD

**Issue by kantaroso** [kantaroso/game-information#19]

**Comment by kantaroso** [comment]
https://rightcode.co.jp/blog/information-technology/vue-js-seo-infinite-scroll

**Comment by kantaroso** [comment]
https://peachscript.github.io/vue-infinite-loading/

**Comment by kantaroso** [comment]
一覧画面ではサムネ+タイトルだけ出すように変更

**Comment by s-kanzaki** [comment]
https://bizyoge.web.app/maker/detail/3rdeye

**Comment by kantaroso** [comment]
https://bizyoge.web.app/maker/detail/3rdeye
